name: rubocop

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Run rubocop
      shell: bash
      run: |
          bundle install
          cd plugin
          bundle exec rubocop -f extension_review -o report.html

    - name: Upload rubocop results as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
          name: Rubocop-${{ github.sha }}-report.html
          path: plugin/report.html
